name: "Deploy on Server"

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4.0.0

      - name: ðŸ”¨ Setup PHP Version
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"

      - name: ðŸš§ Installing Dependencies
        uses: "ramsey/composer-install@v1"

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ftpupload.net
          username: epiz_27447670
          password: ZMPsHnWZuC
          server-dir: htdocs